name: CML with DVC
on:
  push:
    # it is also possible to chose which branch and action to run
    # can also say which to ignore
    branches: [dev]
    # branches-ignore: [main, dev]
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Deploy runner on EC2
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner \
              --cloud=aws \
              --cloud-region=ap-southeast-1c \
              --cloud-type=t2.micro \
              --labels=cml-runner \
              --single
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    timeout-minutes: 120 # 2h
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml ci
          pip install -r requirements.txt

          # reproduce pipeline and data to dvc push
          dvc pull
          dvc repro
          dvc push

          # Create CML report
          echo "## Feature Importance and Selection" >> report.md
          cml publish data/feature_importance.png --md >> report.md
          cml publish data/featureselection.png --md >> report.md

          echo "## Metrics" >> report.md
          cat data/metrics.json > report.md
          
          echo "## Sample Predictions" >> report.md
          cml publish data/sampledailyprediction.png --md >> report.md
          cml send-comment --pr --update report.md